# project.yaml
openapi: 3.0.0
info:
  title: Project API
  version: 1.0.0
paths:
  /:
    post:
      summary: Create a new project
      description: |
        Creates a new project with the provided details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: The title of the project.
                  example: My Project
                description:
                  type: string
                  description: A description of the project.
                  example: This is a sample project.
                startDate:
                  type: string
                  format: date
                  description: The start date of the project.
                  example: 2023-10-05
                endDate:
                  type: string
                  format: date
                  description: The end date of the project.
                  example: 2023-10-31
                estimatedStoryPoints:
                  type: integer
                  description: The estimated story points for the project.
                  example: 10
      responses:
        '201':
          description: Project created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Project created successfully
                  project:
                    type: object
                    properties:
                      _id:
                        type: string
                        example: 5fa3ebd68bfa6a0017e622e9
                      title:
                        type: string
                        example: My Project
                      description:
                        type: string
                        example: This is a sample project.
                      startDate:
                        type: string
                        format: date
                        example: 2023-10-05
                      endDate:
                        type: string
                        format: date
                        example: 2023-10-31
                      estimatedStoryPoints:
                        type: integer
                        example: 10
                      admins:
                        type: array
                        items:
                          type: string
                          example: 5fa3ebd68bfa6a0017e622e9
                      members:
                        type: array
                        items:
                          type: string
                          example: 5fa3ebd68bfa6a0017e622e9
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Internal server error
